server:
  port: 8084
  servlet:
    context-path: /FactoryUpdateDetails

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Factory
    username: postgres
    password: Welcome@123
    platform: postgresql
    

